### ISSUE TITLE
Convert.java - stringToInt( )

### ISSUE THREAD

**Issue by katkeit** [katkeit/SUN-Calculator#22]
There is an error when using the method stringToInt inside the Convert class. This method throws the following Exception when the user inputs characters and no numbers in the Level box.

How to duplicate:
1) Select a class.
2) Input any characters into the Level box.
3) Press Enter.

Exception:

> Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: ""
> 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
> 	at java.base/java.lang.Integer.parseInt(Integer.java:662)
> 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
> 	at utility.Convert.stringToInt(Convert.java:41)
> 	at character.CalcLevel.validateLevel(CalcLevel.java:124)
> 	at character.CalcLevel.actionPerformed(CalcLevel.java:112)
> 	at java.desktop/javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
> 	at java.desktop/javax.swing.JTextField.postActionEvent(JTextField.java:723)
> 	at java.desktop/javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:839)
> 	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
> 	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
> 	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2948)
> 	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
> 	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
> 	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
> 	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
> 	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
> 	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4871)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
>

**Comment by katkeit** [comment]
Issue has been fixed and will be implemented into SUN-Calculator v1.0.0.
